[workspace]
members = ["browser-test", "browser-test-macros"]
exclude = ["examples/advanced", "examples/minimal"]
resolver = "2"

[workspace.package]
version = "0.6.0"
edition = "2024"
rust-version = "1.89.0"
authors = ["Lukas Potthast <privat@lukas-potthast.de>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/lpotthast/browser-test"

[workspace.dependencies]
browser-test-macros = { version = "0.6.0", path = "browser-test-macros" }
rootcause = { version = "0.13.0", default-features = false }

[workspace.lints.rust]
missing_docs = "warn"

[workspace.lints.clippy]
pedantic = "warn"
