[package]
name = "browser-test-advanced-example"
version = "0.1.0"
edition = "2024"
rust-version = "1.89.0"
publish = false

[dependencies]
browser-test = { path = "../../browser-test", default-features = false, features = ["rustls"] }
rootcause = { version = "0.13.0", default-features = false }
rootcause-backtrace = { version = "0.13.0", default-features = false }
rootcause-tracing = { version = "0.13.0", default-features = false }
thiserror = { version = "2.0.18", default-features = false, features = ["std"] }
tokio = { version = "1.52.3", default-features = false, features = ["macros", "rt-multi-thread"] }
tracing = { version = "0.1.44", default-features = false, features = ["attributes", "std"] }
tracing-subscriber = { version = "0.3.23", default-features = false, features = ["ansi", "fmt", "registry"] }
